export type RareBoardCatastropheKind =
    | "earthquake"
    | "tsunami"
    | "lightning"
    | "meteor"
    | "blackhole"
    | "volcano"
    | "ice"
    | "laser"
    | "gravity"
    | "crack"
    | "typhoon"
    | "sandstorm"
    | "aurora"
    | "timebreak"
    | "pinfall"
    | "mirror"
    | "plasma"
    | "labburst"
    | "dragon"
    | "void"
    | "supernova";

export type RareBoardCatastropheDef = {
    kind: RareBoardCatastropheKind;
    label: string;
    emoji: string;
    color: string;
    bg: string;
    shake: number;
    duration: number;
    gravityX: number;
    gravityY: number;
    lightning: number;
    waves: number;
    fragments: number;
};

export const RARE_BOARD_CATASTROPHE_DEFS: RareBoardCatastropheDef[] = [
    {
        kind: "earthquake",
        label: "大地震で盤面崩壊",
        emoji: "🌋",
        color: "#ff6b35",
        bg: "rgba(80,25,10,.28)",
        shake: 56,
        duration: 2600,
        gravityX: 0.16,
        gravityY: 9.8,
        lightning: 2,
        waves: 1,
        fragments: 24,
    },
    {
        kind: "tsunami",
        label: "津波が盤面を飲み込む",
        emoji: "🌊",
        color: "#38bdf8",
        bg: "rgba(14,116,144,.32)",
        shake: 42,
        duration: 2800,
        gravityX: -0.2,
        gravityY: 7.2,
        lightning: 0,
        waves: 5,
        fragments: 12,
    },
    {
        kind: "lightning",
        label: "落雷の嵐",
        emoji: "⚡",
        color: "#fde047",
        bg: "rgba(253,224,71,.18)",
        shake: 48,
        duration: 2400,
        gravityX: 0.08,
        gravityY: 8.0,
        lightning: 14,
        waves: 1,
        fragments: 18,
    },
    {
        kind: "meteor",
        label: "隕石群直撃",
        emoji: "☄️",
        color: "#fb923c",
        bg: "rgba(124,45,18,.30)",
        shake: 60,
        duration: 2800,
        gravityX: -0.08,
        gravityY: 10.8,
        lightning: 5,
        waves: 2,
        fragments: 34,
    },
    {
        kind: "blackhole",
        label: "ブラックホール発生",
        emoji: "🕳️",
        color: "#a78bfa",
        bg: "rgba(30,27,75,.42)",
        shake: 44,
        duration: 3000,
        gravityX: 0,
        gravityY: 4.8,
        lightning: 4,
        waves: 4,
        fragments: 10,
    },
    {
        kind: "volcano",
        label: "火山噴火モード",
        emoji: "🔥",
        color: "#ef4444",
        bg: "rgba(127,29,29,.34)",
        shake: 54,
        duration: 2600,
        gravityX: 0.1,
        gravityY: 11.2,
        lightning: 3,
        waves: 1,
        fragments: 32,
    },
    {
        kind: "ice",
        label: "氷結崩壊",
        emoji: "❄️",
        color: "#bae6fd",
        bg: "rgba(125,211,252,.25)",
        shake: 34,
        duration: 2500,
        gravityX: -0.1,
        gravityY: 6.4,
        lightning: 2,
        waves: 2,
        fragments: 20,
    },
    {
        kind: "laser",
        label: "研究所レーザー暴走",
        emoji: "🔴",
        color: "#ff2d75",
        bg: "rgba(190,24,93,.26)",
        shake: 38,
        duration: 2400,
        gravityX: 0.14,
        gravityY: 8.2,
        lightning: 10,
        waves: 0,
        fragments: 16,
    },
    {
        kind: "gravity",
        label: "重力反転警報",
        emoji: "🧲",
        color: "#22d3ee",
        bg: "rgba(8,145,178,.25)",
        shake: 44,
        duration: 3000,
        gravityX: 0,
        gravityY: -3.2,
        lightning: 3,
        waves: 3,
        fragments: 10,
    },
    {
        kind: "crack",
        label: "盤面亀裂拡大",
        emoji: "🪨",
        color: "#d6d3d1",
        bg: "rgba(41,37,36,.35)",
        shake: 52,
        duration: 2600,
        gravityX: -0.12,
        gravityY: 8.8,
        lightning: 2,
        waves: 2,
        fragments: 28,
    },
    {
        kind: "typhoon",
        label: "超巨大台風",
        emoji: "🌀",
        color: "#67e8f9",
        bg: "rgba(21,94,117,.30)",
        shake: 40,
        duration: 2800,
        gravityX: 0.24,
        gravityY: 6.8,
        lightning: 5,
        waves: 4,
        fragments: 12,
    },
    {
        kind: "sandstorm",
        label: "砂嵐で視界崩壊",
        emoji: "🌪️",
        color: "#fbbf24",
        bg: "rgba(146,64,14,.26)",
        shake: 36,
        duration: 2500,
        gravityX: -0.22,
        gravityY: 7.4,
        lightning: 1,
        waves: 2,
        fragments: 22,
    },
    {
        kind: "aurora",
        label: "オーロラ暴走",
        emoji: "🌌",
        color: "#86efac",
        bg: "rgba(6,78,59,.24)",
        shake: 32,
        duration: 2600,
        gravityX: 0.06,
        gravityY: 5.8,
        lightning: 7,
        waves: 3,
        fragments: 10,
    },
    {
        kind: "timebreak",
        label: "時間断層崩壊",
        emoji: "⏳",
        color: "#c4b5fd",
        bg: "rgba(76,29,149,.30)",
        shake: 42,
        duration: 3000,
        gravityX: 0.04,
        gravityY: 4.2,
        lightning: 8,
        waves: 4,
        fragments: 14,
    },
    {
        kind: "pinfall",
        label: "ピン全域暴走",
        emoji: "📍",
        color: "#fda4af",
        bg: "rgba(159,18,57,.24)",
        shake: 50,
        duration: 2600,
        gravityX: -0.14,
        gravityY: 8.4,
        lightning: 4,
        waves: 2,
        fragments: 26,
    },
    {
        kind: "mirror",
        label: "鏡面世界反転",
        emoji: "🪞",
        color: "#e0f2fe",
        bg: "rgba(15,23,42,.26)",
        shake: 34,
        duration: 2500,
        gravityX: 0.18,
        gravityY: 6.2,
        lightning: 4,
        waves: 3,
        fragments: 12,
    },
    {
        kind: "plasma",
        label: "プラズマ豪雨",
        emoji: "💥",
        color: "#f0abfc",
        bg: "rgba(112,26,117,.30)",
        shake: 46,
        duration: 2500,
        gravityX: 0.1,
        gravityY: 9.2,
        lightning: 12,
        waves: 2,
        fragments: 18,
    },
    {
        kind: "labburst",
        label: "研究炉メルトダウン",
        emoji: "☢️",
        color: "#bef264",
        bg: "rgba(63,98,18,.24)",
        shake: 58,
        duration: 2800,
        gravityX: -0.1,
        gravityY: 10.0,
        lightning: 6,
        waves: 2,
        fragments: 32,
    },
    {
        kind: "dragon",
        label: "龍脈が盤面を裂く",
        emoji: "🐉",
        color: "#34d399",
        bg: "rgba(6,95,70,.28)",
        shake: 52,
        duration: 2700,
        gravityX: 0.2,
        gravityY: 8.0,
        lightning: 8,
        waves: 4,
        fragments: 20,
    },
    {
        kind: "void",
        label: "虚無領域展開",
        emoji: "⬛",
        color: "#e5e7eb",
        bg: "rgba(0,0,0,.44)",
        shake: 40,
        duration: 2900,
        gravityX: 0,
        gravityY: 3.6,
        lightning: 2,
        waves: 5,
        fragments: 8,
    },
    {
        kind: "supernova",
        label: "超新星爆発",
        emoji: "🌟",
        color: "#fff7ad",
        bg: "rgba(250,204,21,.26)",
        shake: 66,
        duration: 3000,
        gravityX: 0.02,
        gravityY: 10.5,
        lightning: 16,
        waves: 6,
        fragments: 38,
    },
];
